export const API_ROUTES = {
  LOGIN: 'login',
  LOGOUT: 'user/logout',
  REGISTER: 'register',
  SOCIAL_LOGIN: 'social-login',
  APP_INFO: 'info',
  GET_LANGUAGES: 'languages',
  VERIFY_EMAIL: 'verify-otp',
  RESET_PASSWORD: 'reset-password',
  VERIFY_OTP: 'verify-code',
  RESEND_OTP: 'resend-otp',
  HOME: 'user/home',
  GET_PROFILE: 'user/user',
  GET_USER_BY_ID: (id: number) => `user/user/${id}`,
  RESEND_VERFICATION: 'resend-otp',
  CONTACT_US: 'contact/create',
  COMPLETE_PROFILE: 'user/onboarding',

  REFRESH_TOKEN: 'token/refresh',
  FORGOT_PASSWORD: 'forgot-password',
  CHANGE_PASSWORD: 'user/update-password',
  SEND_OTP: 'otp/send',
  LOGOUT_ALL: 'logout/all',
  EMAIL_UNSUBSCRIBE: 'email/unsubscribe',
  UPDATE_PROFILE: 'user/update',
  UPLOAD_PROFILE_PICTURE: 'user/profile/picture/upload',
  DELETE_PROFILE_PICTURE: 'user/profile/picture/delete',
  UPDATE_CONTACT_INFO: 'user/profile/contact',
  UPDATE_ADDRESS: 'user/profile/address',
  GET_USER_SETTINGS: 'user/settings',
  UPDATE_USER_SETTINGS: 'user/settings/update',
  DELETE_ACCOUNT: 'user/delete-account',
  DEACTIVATE_ACCOUNT: 'user/account/deactivate',
  GET_NOTIFICATIONS: 'notification',
  MARK_NOTIFICATION_AS_READ: 'notifications/read',
  DELETE_NOTIFICATION: 'notifications/delete',
  SEND_MESSAGE_NOTIFICATION: 'notification/send-message',
  SEND_MESSAGE: 'messages/send',
  GET_MESSAGES: 'messages',
  DELETE_MESSAGE: 'messages/delete',
  GET_MESSAGE_CONVERSATION: 'messages/conversation',
  GET_USER_ROLES: 'user/roles',
  ASSIGN_ROLE_TO_USER: 'user/roles/assign',
  REMOVE_ROLE_FROM_USER: 'user/roles/remove',
  GET_PERMISSIONS: 'user/permissions',
  GRANT_PERMISSION: 'user/permissions/grant',
  REVOKE_PERMISSION: 'user/permissions/revoke',
  GET_USER_ACTIVITY_LOG: 'user/activity',
  GET_SYSTEM_LOGS: 'system/logs',
  GET_ERROR_LOGS: 'system/logs/errors',
  GET_LOGIN_HISTORY: 'user/login-history',
  CLEAR_USER_ACTIVITY_LOG: 'user/activity/clear',
  GET_BILLING_INFO: 'user/billing',
  UPDATE_BILLING_INFO: 'user/billing/update',
  GET_PAYMENT_HISTORY: 'user/payments',
  MAKE_PAYMENT: 'payments/make',
  REFUND_PAYMENT: 'payments/refund',
  GET_PAYMENT_METHODS: 'payments/methods',
  ADD_PAYMENT_METHOD: 'payments/method/add',
  DELETE_PAYMENT_METHOD: 'payments/method/delete',
  GET_USER_POSTS: 'posts/user',
  CREATE_POST: 'posts/create',
  UPDATE_POST: 'posts/update',
  DELETE_POST: 'posts/delete',
  LIKE_POST: 'posts/like',
  COMMENT_ON_POST: 'posts/comment',
  GET_COMMENTS: 'posts/comments',
  DELETE_COMMENT: 'posts/comments/delete',
  GET_POST_LIKES: 'posts/likes',
  UPLOAD_FILE: 'files/upload',
  GET_FILE: 'files/get',
  DELETE_FILE: 'files/delete',
  GET_FILE_LIST: 'files/list',
  UPDATE_FILE_METADATA: 'files/metadata/update',
  GET_USER_MEDIA: 'user/media',

  FOLLOW_USER: 'users/follow',
  UNFOLLOW_USER: 'users/unfollow',
  GET_FOLLOWERS: 'users/followers',
  GET_FOLLOWING: 'users/following',
  BLOCK_USER: 'users/block',
  UNBLOCK_USER: 'users/unblock',

  GET_USERS_LIST: 'admin/users',
  GET_USER_DETAILS: 'admin/user/details',
  DELETE_USER: 'admin/user/delete',
  GET_ALL_ROLES: 'admin/roles',
  CREATE_ROLE: 'admin/roles/create',
  UPDATE_ROLE: 'admin/roles/update',
  DELETE_ROLE: 'admin/roles/delete',
  GET_SITE_STATS: 'stats',
  GET_HELP_CENTER: 'help',
  GET_TERMS_AND_CONDITIONS: 'content/terms-and-conditions',
  GET_CANCELLATION_POLICY: 'content/cancellation-policy',
  GET_PRIVACY_POLICY: 'content/privacy-policy',
  GET_ABOUT_US: 'content/about-us',
  SEND_FEEDBACK: 'feedback/send',
  GET_FAQ: 'faq',

  //motivault
  GET_SERVICES_LIST: 'service',
  GET_CATEGORIES: 'static/categories',
  TOGGLE_FAVOURITE: 'favourites/toggle',
  GET_CATEGORIES_ITEM: 'items/events/tickets/?',
  GET_CATEGORIES_VENDOR: 'vendor/',
  GET_ITEM_CATEGORIES: 'item_categories/',
  GET_RATING_BY_ITEM_ID: 'reviews/item/',
  GET_VENDOR_ITEMS_BY_ID: 'items/',
  GET_GALLERY_BY_ITEM_ID: 'gallery/item/',
  POST_RATING: 'reviews',
  GET_SUB_CATEGORIES: '',
  BOOK_SERVICE_PROVIDER: 'userbooking/create',

  GET_USER_BOOKINGS_LIST: 'userbooking',
  GET_DENTOR_BOOKINGS_LIST: 'dentorbooking',
  REQUEST_WITHDRAW_AMOUNT: 'wallet/withdrawal/request',
  STRIPE_CONNECT_LINK: 'wallet/stripe-connect/link',
  GET_WALLET: 'wallet',

  // Dentor: Bidding & Quotation
  DENTOR_CREATE_QUOTATION: 'dentorbooking/quotation',
  DENTOR_UPDATE_QUOTATION: (id: number) => `dentorbooking/quotation/${id}`,
  DENTOR_UPDATE_BOOKING_STATUS: (id: number) => `dentorbooking/${id}/status`,
  DENTOR_SUBMIT_PROOF: (id: number) => `dentorbooking/${id}/submit-proof`,

  // User: Quotation accept/reject & Booking
  USER_QUOTATIONS_LIST: (bookingId: number) => `userbooking/${bookingId}/quotations`,
  USER_ACCEPT_REJECT_QUOTATION: (id: number) => `userbooking/quotation/${id}`,
  /** Get PaymentIntent for quotation - POST userbooking/stripe/payment-intent */
  USER_STRIPE_PAYMENT_INTENT: 'userbooking/stripe/payment-intent',
  /** Create SetupIntent for saving cards - POST payment/create-setup-intent */
  PAYMENT_GET_SETUP_INTENT: 'payment/create-setup-intent',
  USER_CANCEL_BOOKING: (id: number) => `userbooking/${id}/cancel`,
  USER_APPROVE_WORK: (id: number) => `userbooking/${id}/approve-work`,
  USER_STRIPE_TIP_PAYMENT: 'userbooking/stripe/tip/payment',

  // Reviews
  GET_REVIEWS: 'review',
  CREATE_REVIEW: 'review/create',

  // Address
  ADDRESS_LIST: 'address',
  ADDRESS_CREATE: 'address/create',
  ADDRESS_UPDATE: (id: number) => `address/${id}`,
  ADDRESS_DELETE: (id: number) => `address/${id}`,

  // Chat / Conversation
  CONVERSATION_CREATE: 'conversation/store/private',
  CONVERSATION_LIST: 'conversation/single-conversation',
  CONVERSATION_MESSAGES: (id: string | number) => `message/${id}`,
};
